
const ADD_TO_BASKET =  "ADD_TO_BASKET";
const REMOVE_FROM_BASKET = "REMOVE_FROM_BASKET";
const TOGGLE_LOGIN_MENU = "TOGGLE_LOGIN_MENU";
const IS_ADMIN = "IS_ADMIN";
const REMOVE_FROM_NUMBERINSTORE = "REMOVE_FROM_NUMBERINSTORE";
const ADD_BACK_TO_NUMBERINSTORE = "ADD_BACK_TO_NUMBERINSTORE";
const EMPTY_BASKET = "EMPTY_BASKET";
const CHANGE_PAGE = "CHANGE_PAGE";

const REMOVE_PRODUCT = 'REMOVE_PRODUCT';
const ADD_PRODUCT = 'ADD_PRODUCT';
const SAVE_CHANGED_PRODUCT = 'SAVE_CHANGED_PRODUCT';


export {ADD_TO_BASKET, REMOVE_FROM_BASKET , TOGGLE_LOGIN_MENU ,
   IS_ADMIN, REMOVE_FROM_NUMBERINSTORE,ADD_BACK_TO_NUMBERINSTORE,EMPTY_BASKET,CHANGE_PAGE,
    REMOVE_PRODUCT,ADD_PRODUCT,SAVE_CHANGED_PRODUCT};
