
const ADD_TO_BASKET =  "ADD_TO_BASKET";
const REMOVE_FROM_BASKET = "REMOVE_FROM_BASKET";
const TOGGLE_LOGIN_MENU = "TOGGLE_LOGIN_MENU";
const IS_ADMIN = "IS_ADMIN";


export {ADD_TO_BASKET, REMOVE_FROM_BASKET , TOGGLE_LOGIN_MENU , IS_ADMIN};
